export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const USER_ROLE_INIT = "USER_ROLE_INIT";
export const USER_ROLE_SUCCESS = "USER_ROLE_SUCCESS";
export const USER_ROLE_FAIL = "USER_ROLE_FAIL";

export const SIGN_OUT = "SIGN_UP_FAIL";

export const SIGN_IN_USER_INIT = "SIGN_IN_USER_INIT";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAIL = "SIGN_IN_USER_FAIL";

// Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

// For Create Corporate User Api
export const CREATE_CORPORATE_USER_INIT = "CREATE_CORPORATE_USER_INIT";
export const CREATE_CORPORATE_USER_SUCCESS = "CREATE_CORPORATE_USER_SUCCESS";
export const CREATE_CORPORATE_USER_FAIL = "CREATE_CORPORATE_USER_FAIL";

// For Send Email Reset Password Api
export const SEND_EMAIL_RESET_PASSWORD_INIT = "SEND_EMAIL_RESET_PASSWORD_INIT";
export const SEND_EMAIL_RESET_PASSWORD_SUCCESS =
  "SEND_EMAIL_RESET_PASSWORD_SUCCESS";
export const SEND_EMAIL_RESET_PASSWORD_FAIL = "SEND_EMAIL_RESET_PASSWORD_FAIL";
